"""The episode dossier: one call, one episode, its entire history.

This is the object the whole design points at.  An episode is the unit of reconciliation, and
everything else — records, verdicts, cash, keys, parks — hangs off it.  Until now those lived in
six tables and were assembled ad hoc by whoever needed them.  This module assembles them **once**,
into the shape a human reads and the agent layer consumes, so both work from the same picture.

═══ Why it is a merged timeline rather than six lists ══════════════════════════════

The question an operator actually asks is *"what happened to this claim?"* — and the answer runs in
one direction, through time, mixing things that happened in the outside world with things we
concluded about them:

    2 Sep    the claim was filed and the PBM accepted it
    18 Sep   the payer's remittance said it paid, short by $500
    17 Sep   the money arrived, matching what the remittance promised
    4 Oct    the TPA said the dispense qualified for 340B
    2 Nov    the manufacturer paid the rebate
    6 Nov    a later remittance clawed $412.60 back, netted, invisible to the bank
    6 Nov    we reopened it: this had been closed since 1 October

Six separate lists cannot be read that way.  A merged, ordered narrative can.

═══ Two clocks, and why both are shown ════════════════════════════════════════════

Every event carries **when we learned it** (``at``, the arrival time) and, where one exists, **when
it happened** (``occurred_on``, a native date on the record).  They are routinely different, and the
gap is often the finding: a remittance dated the 17th that reached us on the 30th is a late-arriving
record, and reading only one clock hides it.

The timeline is ordered by ``at``, because that is the order the system could have known things —
which is the same order replay reproduces.

═══ Verdicts appear as *transitions*, not as samples ══════════════════════════════

The engine writes a verdict per (episode, cursor), so an episode evaluated monthly has a dozen rows
saying the same thing.  Listing all of them buries the two that matter.  Only changes are emitted —
the first verdict, and every later one that differs — with what changed spelled out.  The full log
is still returned separately for anyone who wants it.

═══ Tags and facts, not sentences ═════════════════════════════════════════════════

An event is a **tag** and its **facts** — never prose.  The tag names what kind of thing happened;
the facts are that record's own fields, carried verbatim, with absent ones omitted.

This is deliberate, and it is the opposite of what this module used to do.  An earlier version
composed English for every event across 51 hand-written branches, including clauses that explained
the domain and the architecture to the reader.  Two things were wrong with that.  It made the
prototype look as though it could describe any record, when it could only describe the branches
somebody had written out — new data would have fallen through to nothing.  And it did the agent
layer's job, badly, one layer too early: a model can already read ``TPA_QUALIFICATION`` with
``qualification_status = QUALIFIED`` and say what it means, which is precisely what the agent layer
is for.

So this module states; it does not narrate.  Nothing here is generated by a model either — every
value is read out of the database, and the agent never sees a figure this module did not read.
"""

from __future__ import annotations

import json
import sqlite3
from dataclasses import asdict, dataclass, field
from typing import Any

from recon.db import repository
from recon.domain.enums import KeyType, RecordKind
from recon.reference import drugs, entities

#: Key types held back from the **dossier**, which is the agent's view.  They stay in the
#: database and stay on the operator's ``/trace``, which is the honest place for them.
#:
#: Both are *restatements of an identity already in this list*, not additional matches:
#:
#: * ``COVERED_ENTITY_340B`` is the covered entity joined to a natural key that is already
#:   here (E1), and the covered entity itself is already in the identity block.
#: * ``HCPCS`` is the same provider, drug and date as the episode's ``NATURAL_340B_MEDICAL``
#:   key, with the drug named by J-code instead of NDC (E2).  It exists so a record that
#:   carries only a J-code can resolve, which is a real capability — but on an episode that
#:   already publishes the NDC form, it is the same claim spelled twice.
#:
#: What this prevents is specific.  A medical episode publishes both forms, so an unfiltered
#: list shows eight rows for four claims — and "more keys than claims" is exactly how a
#: duplicate looks to anything reading this structure, including a careful human.
#:
#: **This is a display rule and nothing else.**  It narrows no resolution: every one of these
#: keys is live in ``crosswalk_key`` and resolves records normally.  And it is scoped to
#: *published* keys — if one of these is ever the **basis** on which something resolved, that
#: is a fact about the match rather than a restatement of one, and it belongs in the dossier.
_DERIVED_KEY_TYPES = frozenset({KeyType.COVERED_ENTITY_340B, KeyType.HCPCS})

__all__ = ["build_dossier", "TimelineEvent", "RECORD_PROJECTIONS"]


@dataclass
class TimelineEvent:
    """One thing that happened, or one thing we concluded.

    A tag and its facts.  No prose — see the projection section below for why.
    """

    #: When we learned it. Ordering key, because it is the order replay reproduces.
    at: str
    #: When it happened in the outside world, where the record carries such a date.
    occurred_on: str | None
    #: What kind of thing this is: a ``RecordKind``, or ``CASH`` / ``VERDICT``.
    tag: str
    #: The fields of this record worth surfacing, carried verbatim. Absent fields
    #: are omitted rather than nulled, so the key set states what the record has.
    facts: dict[str, Any] = field(default_factory=dict)
    #: The subset of ``facts`` that carries the story rather than the identity.
    #: A short view shows these; a full view shows everything. Both read one object.
    essential: tuple[str, ...] = ()
    #: Where to look it up: the feed file, the line, the source record id.
    source: dict[str, Any] | None = None
    #: True when arrival lagged the event by more than a fortnight — the late-arrival defect.
    late: bool = False


def build_dossier(conn: sqlite3.Connection, episode_id: str, cursor: str) -> dict[str, Any] | None:
    """Everything known about one episode, as of ``cursor``.

    The cursor is honoured throughout: at an earlier cursor the dossier is genuinely shorter, because
    records that had not arrived are not part of the story yet.  That is the same replay property the
    rest of the system has, applied to the narrative.
    """
    episode = conn.execute(
        "SELECT * FROM episode WHERE episode_id = ?", (episode_id,)
    ).fetchone()
    if episode is None:
        return None

    records = _records(conn, episode_id, cursor)
    allocations = _allocations(conn, episode_id, cursor)
    verdicts = repository.verdict_history(conn, episode_id)
    visible_verdicts = [v for v in verdicts if v.cursor_at <= cursor]

    events: list[TimelineEvent] = []
    events.extend(_record_events(records))
    events.extend(_cash_events(allocations))
    events.extend(_verdict_events(visible_verdicts))
    events.sort(key=lambda event: (event.at, event.tag))

    latest = visible_verdicts[-1] if visible_verdicts else None
    return {
        "episode_id": episode_id,
        "cursor": cursor,
        "identity": _identity(episode),
        "current": _current(latest),
        "economics": _economics(latest),
        "timeline": [asdict(event) for event in events],
        "counts": {
            "records": len(records),
            "cash_allocations": len(allocations),
            "verdicts_written": len(visible_verdicts),
            "verdict_changes": sum(1 for e in events if e.tag == "VERDICT"),
        },
        # The raw material, for anyone who wants to check the narrative against it.
        "verdict_log": [
            {
                "cursor_at": v.cursor_at,
                "episode_disposition": v.episode_disposition.value,
                "reimbursement_verdict": v.reimbursement_verdict_code,
                "rebate_verdict": v.rebate_verdict_code,
                "reason_codes": [code.value for code in v.reasons],
                "reopened_from": v.reopened_from.value if v.reopened_from else None,
            }
            for v in visible_verdicts
        ],
        "crosswalk_keys": [
            {
                "key_type": row.key_type.value,
                "key_value": row.key_value,
                "first_seen_at": row.first_seen_at,
            }
            for row in repository.crosswalk_for_episode(conn, episode_id)
            if row.first_seen_at <= cursor and row.key_type not in _DERIVED_KEY_TYPES
        ],
        "unresolved": _unresolved(conn, episode, cursor),
    }


# ═══ identity and headline figures ══════════════════════════════════════════


def _identity(episode: sqlite3.Row) -> dict[str, Any]:
    try:
        drug = drugs.by_ndc(episode["ndc11"])
        drug_name = f"{drug.name} {drug.strength}"
    except Exception:
        drug_name = episode["ndc11"]

    payer_id = episode["pbm_id"] or episode["medical_payer_id"]
    payer_name = payer_id
    try:
        payer_name = (
            entities.pbm_by_id(payer_id).name
            if episode["pbm_id"]
            else entities.payer_by_id(payer_id).name
        )
    except Exception:
        pass

    return {
        "track": episode["reimbursement_track"],
        "drug": drug_name,
        "ndc11": episode["ndc11"],
        "quantity": (episode["quantity_milli"] or 0) // 1000,
        "date_of_service": episode["date_of_service"],
        "payer": payer_name,
        "pharmacy_npi": episode["pharmacy_npi"],
        "rx_number": episode["rx_number"],
        "fill_number": episode["fill_number"],
        "clm01": episode["clm01"],
        "billing_provider_npi": episode["billing_provider_npi"],
        "is_340b_flagged": bool(episode["is_340b_flagged"]),
        "opened_at": episode["created_from_received_at"],
    }


def _current(latest) -> dict[str, Any] | None:
    if latest is None:
        return None
    return {
        "reimbursement_verdict": latest.reimbursement_verdict_code,
        "rebate_verdict": latest.rebate_verdict_code,
        "episode_disposition": latest.episode_disposition.value,
        "reason_codes": [code.value for code in latest.reasons],
        "cross_track_flags": [flag.code for flag in latest.cross_track_flags],
        "reopened_from": latest.reopened_from.value if latest.reopened_from else None,
        "as_of": latest.cursor_at,
    }


def _economics(latest) -> dict[str, Any] | None:
    if latest is None:
        return None
    return {
        "expected_reimbursement_cents": latest.expected_reimbursement_cents,
        "received_reimbursement_cents": latest.received_reimbursement_cents,
        "reimbursement_variance_cents": latest.reimbursement_variance_cents,
        "expected_rebate_cents": latest.expected_rebate_cents,
        "received_rebate_cents": latest.received_rebate_cents,
        "rebate_variance_cents": latest.rebate_variance_cents,
    }


# ═══ fetching ═══════════════════════════════════════════════════════════════


def _records(conn: sqlite3.Connection, episode_id: str, cursor: str) -> list[sqlite3.Row]:
    """Every record that resolved to this episode, in arrival order.

    Driven by ``ix_crosswalk_episode`` — the crosswalk already knows what points here, so this is a
    seek rather than a hunt through the record table.
    """
    return conn.execute(
        "SELECT DISTINCT n.norm_id, n.raw_id, n.record_kind, n.source_system, n.received_at,"
        "       n.amount_cents, n.status_code, n.canonical, n.date_of_service, n.clp07,"
        "       n.rx_number, n.authorization_number, n.allocation_code, n.trn02,"
        "       r.source_record_id, r.source_line_no, b.source_file"
        "  FROM crosswalk_key k"
        "  JOIN normalized_record n ON n.norm_id = k.resolved_from_norm_id"
        "  JOIN raw_record r ON r.raw_id = n.raw_id"
        "  JOIN ingest_batch b ON b.batch_id = r.batch_id"
        " WHERE k.episode_id = :episode_id AND n.received_at <= :cursor"
        " ORDER BY n.received_at, n.norm_id",
        {"episode_id": episode_id, "cursor": cursor},
    ).fetchall()


def _allocations(conn: sqlite3.Connection, episode_id: str, cursor: str) -> list[sqlite3.Row]:
    return conn.execute(
        "SELECT a.allocated_cents, a.basis, a.caused_by_received_at,"
        "       bank.canonical AS bank_canonical, bank.ach_trace_number, bank.trn02,"
        "       parent.record_kind AS parent_kind"
        "  FROM cash_allocation a"
        "  JOIN normalized_record bank ON bank.norm_id = a.bank_norm_id"
        "  LEFT JOIN normalized_record parent ON parent.norm_id = a.remittance_norm_id"
        " WHERE a.episode_id = :episode_id AND a.caused_by_received_at <= :cursor"
        " ORDER BY a.caused_by_received_at, a.allocation_id",
        {"episode_id": episode_id, "cursor": cursor},
    ).fetchall()


def _unresolved(conn: sqlite3.Connection, episode: sqlite3.Row, cursor: str) -> list[dict[str, Any]]:
    """Records that *tried* to reach this episode and could not.

    A crosswalk miss leaves nothing attached to the episode, so by definition it cannot appear in the
    timeline — which is precisely why it needs saying somewhere.  These are parked records whose keys
    overlap this episode's natural key, i.e. documents that are probably about this claim but whose
    identifiers did not match.  D-6, from the episode's point of view.
    """
    if not episode["rx_number"]:
        return []
    rows = conn.execute(
        "SELECT DISTINCT p.record_kind, p.park_reason, p.received_at, k.key_type, k.key_value"
        "  FROM parked_record p"
        "  JOIN parked_record_key k ON k.parked_id = p.parked_id"
        "  LEFT JOIN parked_record_resolution r ON r.parked_id = p.parked_id"
        " WHERE r.parked_id IS NULL AND p.received_at <= :cursor"
        "   AND k.key_value LIKE :like"
        " ORDER BY p.received_at",
        {"cursor": cursor, "like": f"%{episode['rx_number']}%"},
    ).fetchall()
    return [
        {
            "record_kind": row["record_kind"],
            "park_reason": row["park_reason"],
            "received_at": row["received_at"],
            "key_type": row["key_type"],
            "key_value": row["key_value"],
        }
        for row in rows
    ]


# ═══ records as a tag and its facts ═════════════════════════════════════════
#
# There are no sentences here, and that is the design rather than an omission.
#
# This object exists to be handed to the agent layer when an episode needs
# explaining.  A model can already turn "TPA_QUALIFICATION, qualification_status
# = QUALIFIED" into a sentence; writing that sentence here would be doing the
# agent's job, in the deterministic layer, in a voice that cannot generalise to
# data it has not seen.  An earlier version did exactly that -- 51 branches
# producing hand-written prose, including clauses that explained the
# architecture to the reader -- which made the prototype look like it could
# narrate arbitrary records when in fact it could only narrate the branches
# somebody had written out.
#
# So an event is a TAG and its FACTS.  The tag says what kind of thing happened;
# the facts are the fields of that record worth surfacing, carried verbatim.
# One projection per RecordKind, and the renderer drops whatever is absent.
#
# Dropping absent fields is what lets flat per-kind lists cover a field space
# that genuinely varies:
#
#   * The four TPA kinds share one adapter dict, so each carries all eleven keys
#     with only its own populated.  Their status discriminators
#     (qualification_status, manufacturer_status) are always present on the kind
#     that owns them, which is what makes a null disqualification_reason safely
#     readable as "qualified" rather than as missing data.
#   * REMITTANCE and REMITTANCE_CLAIM_LINE are each built by two adapters.  The
#     PBM path emits payer_name and a singular service_line; the medical path
#     emits payer_tin and a plural service_lines list.  The service-line split is
#     real and documented -- a pharmacy claim genuinely is one line, a medical
#     infusion is one J-code plus up to two administration CPTs
#     (docs/feed_formats.md, Section 2).  The payer_name/payer_tin split is not
#     documented anywhere and looks incidental; both keys are listed so neither
#     channel silently renders nothing.
#
# Money stays as integer cents.  Formatting is the display edge's job, and the
# agent wants the exact figure, not a rounded string.


@dataclass(frozen=True)
class Projection:
    """Which fields of a record are worth surfacing, and where they come from."""

    #: Keys read out of the parsed ``canonical`` JSON body.
    body: tuple[str, ...] = ()
    #: Columns read straight off the ``normalized_record`` row.
    row: tuple[str, ...] = ()
    #: The subset that carries the *story*: what happened and what it was worth.
    #:
    #: Everything else in ``body``/``row`` is identity -- an ICN, a covered-entity
    #: id, a wholesaler invoice number, an authorization number.  Those matter when
    #: you are chasing one record down to its source, and they are noise when you
    #: are reading a timeline to work out what happened to a claim.  Reading
    #: "HIN HN3021998, covered entity DSH310074, invoice WI-88213" tells you
    #: nothing about the episode; "QUALIFIED" tells you everything.
    #:
    #: The split lives here rather than in the front end on purpose: the agent
    #: layer wants the same short view a person does, and a filter implemented in
    #: React would be invisible to it.
    simple: tuple[str, ...] = ()


#: Public name (spec_fixes_round1.md B8): the agent layer (`recon.agents.tools`)
#: reads this table to derive which fields are feed-derived and must be fenced
#: before a model sees them -- importing another layer's underscore-private to do
#: that was itself a reviewer finding (17). `_PROJECTIONS` is kept as an alias
#: immediately below rather than removed: other modules in this tree already
#: import the private name directly, and this fixer's mandate is one authorised
#: edit to this file, not a repo-wide rename of every call site.
RECORD_PROJECTIONS: dict[RecordKind, Projection] = {
    RecordKind.PHARMACY_CLAIM: Projection(
        body=(
            "transaction_code", "response_status", "reject_codes",
            "submission_clarification_code", "ingredient_cost_paid_cents",
            "dispensing_fee_paid_cents", "patient_pay_amount_cents",
            "total_amount_paid_cents",
        ),
        row=("authorization_number", "rx_number"),
        # Paid or rejected, for how much, and whether it was flagged 340B at the
        # counter. The ingredient/dispensing split is detail; the total is the story.
        simple=(
            "response_status", "reject_codes", "total_amount_paid_cents",
            "patient_pay_amount_cents", "submission_clarification_code",
        ),
    ),
    RecordKind.PHARMACY_REVERSAL: Projection(
        body=("transaction_code", "response_status", "reversal_reason"),
        row=("authorization_number", "rx_number"),
        simple=("reversal_reason",),
    ),
    RecordKind.REMITTANCE: Projection(
        # payer_name is the PBM path, payer_tin the medical one -- see the note above.
        body=(
            "payer_name", "payer_tin", "payment_method_code",
            "payment_effective_date", "claim_line_count",
        ),
        row=("trn02", "amount_cents"),
        simple=("amount_cents", "claim_line_count", "payment_effective_date"),
    ),
    RecordKind.REMITTANCE_CLAIM_LINE: Projection(
        # service_line singular is PBM, service_lines plural is medical.
        body=(
            "clp01", "clp02_claim_status_code", "charge_cents", "payment_cents",
            "patient_responsibility_cents", "adjustments", "service_line",
            "service_lines",
        ),
        row=("clp07", "amount_cents"),
        # Charged, paid, why the difference, and whether the receivable closed.
        simple=(
            "clp02_claim_status_code", "charge_cents", "payment_cents", "adjustments",
        ),
    ),
    RecordKind.PROVIDER_LEVEL_ADJUSTMENT: Projection(
        body=("reason_code", "amount_cents", "reference"),
        simple=("reason_code", "amount_cents"),
    ),
    RecordKind.MEDICAL_SUBMISSION: Projection(
        body=(
            "frequency_code", "ref_f8_original_icn", "rendering_provider_npi",
            "service_lines", "ctp04_quantity", "ctp05_uom_qualifier",
        ),
        # frequency_code is the one that matters: original, replacement or void.
        simple=("frequency_code", "service_lines"),
    ),
    RecordKind.MEDICAL_ACKNOWLEDGMENT: Projection(
        body=("stc01_composite", "stc12_free_form", "accepted"),
        row=("clp07",),
        # The free-form text alone: "ACCEPTED FOR PROCESSING" on the happy path,
        # "MISSING OR INVALID SUBSCRIBER ID" on a rejection. Carrying `accepted`
        # beside it restates the same fact twice in the cases where it is true.
        simple=("stc12_free_form",),
    ),
    RecordKind.TPA_QUALIFICATION: Projection(
        body=(
            "event_type", "qualification_status", "disqualification_reason",
            "covered_entity_id", "hin", "wholesaler_invoice_number",
        ),
        simple=("qualification_status", "disqualification_reason"),
    ),
    RecordKind.TPA_REBATE_REQUEST: Projection(
        body=("event_type", "manufacturer", "submission_date", "covered_entity_id"),
        simple=("manufacturer", "submission_date"),
    ),
    RecordKind.TPA_MANUFACTURER_DECISION: Projection(
        body=("event_type", "manufacturer_status", "rejection_reason", "covered_entity_id"),
        simple=("manufacturer_status", "rejection_reason"),
    ),
    RecordKind.TPA_REVERSAL: Projection(
        body=("event_type", "quantity_dispensed", "reversal_reason", "covered_entity_id"),
        simple=("quantity_dispensed", "reversal_reason"),
    ),
    RecordKind.REBATE_BATCH: Projection(
        body=("event_type", "manufacturer", "payment_effective_date", "dispense_line_count"),
        row=("allocation_code", "amount_cents"),
        simple=("manufacturer", "amount_cents", "payment_effective_date"),
    ),
    RecordKind.REBATE_DISPENSE_LINE: Projection(
        body=("manufacturer_status", "covered_entity_id", "rebate_amount_cents"),
        row=("allocation_code",),
        simple=("manufacturer_status", "rebate_amount_cents"),
    ),
    RecordKind.BANK_TRANSACTION: Projection(
        body=(
            "posting_date", "description", "company_name", "company_id",
            "company_entry_description", "direction", "running_balance_cents",
        ),
        row=("trn02", "amount_cents"),
        simple=("direction", "amount_cents", "posting_date"),
    ),
}

#: Backward-compatible alias -- see the note on `RECORD_PROJECTIONS` above.
_PROJECTIONS = RECORD_PROJECTIONS


# Every projection's `simple` must be a subset of what it actually surfaces,
# otherwise the short view silently asks for a field that can never appear.
for _kind, _p in _PROJECTIONS.items():
    _unknown = set(_p.simple) - set(_p.body) - set(_p.row)
    if _unknown:  # pragma: no cover - guard whose job is to never fire
        raise RuntimeError(f"{_kind}: simple names fields it does not project: {sorted(_unknown)}")


# Every kind gets a row.  The previous version skipped unknown kinds with a bare
# `continue`, so four record kinds -- REMITTANCE, BANK_TRANSACTION, REBATE_BATCH
# and a phantom MEDICAL_SUBMISSION_LINE -- vanished from every episode history
# with no error anywhere.  A gap should fail here, at import, not disappear.
_UNPROJECTED = sorted(set(RecordKind) - set(_PROJECTIONS))
if _UNPROJECTED:  # pragma: no cover - a guard whose whole job is to never fire
    raise RuntimeError(
        f"dossier projections missing for {_UNPROJECTED}. Every RecordKind needs one, "
        "or its records disappear from the timeline silently."
    )


def _source(row: sqlite3.Row) -> dict[str, Any]:
    return {
        "file": row["source_file"],
        "line": row["source_line_no"],
        "record_id": row["source_record_id"],
        "norm_id": row["norm_id"],
        "raw_id": row["raw_id"],
    }


def _is_late(received_at: str, occurred_on: str | None) -> bool:
    """Arrival lagging the event by more than a fortnight — the D-2 shape."""
    if not occurred_on:
        return False
    from datetime import date

    try:
        return (date.fromisoformat(received_at[:10]) - date.fromisoformat(occurred_on)).days > 14
    except ValueError:
        return False


def _present(value: Any) -> bool:
    """Absent means no key, null, or an empty collection — not ``False`` or ``0``.

    ``accepted: false`` on an acknowledgment and ``payment_cents: 0`` on a denied
    line are both facts worth stating, so only genuine absence is dropped.
    """
    if value is None:
        return False
    if isinstance(value, (list, dict, str)) and len(value) == 0:
        return False
    return True


def _facts(projection: Projection, row: sqlite3.Row, body: dict[str, Any]) -> dict[str, Any]:
    facts: dict[str, Any] = {}
    for name in projection.row:
        value = row[name]
        if _present(value):
            facts[name] = value
    for name in projection.body:
        value = body.get(name)
        if _present(value):
            facts[name] = value
    return facts


def _record_events(records: list[sqlite3.Row]) -> list[TimelineEvent]:
    events: list[TimelineEvent] = []
    for row in records:
        kind = RecordKind(row["record_kind"])
        projection = _PROJECTIONS[kind]
        body = json.loads(row["canonical"])
        occurred = row["date_of_service"]
        facts = _facts(projection, row, body)
        events.append(
            TimelineEvent(
                at=row["received_at"],
                occurred_on=occurred,
                tag=str(kind),
                facts=facts,
                # Intersected with what is actually present, so `essential` never
                # names a key the consumer cannot find in `facts`.
                essential=tuple(name for name in projection.simple if name in facts),
                source=_source(row),
                late=_is_late(row["received_at"], occurred),
            )
        )
    return events


# ═══ cash ═══════════════════════════════════════════════════════════════════


def _cash_events(allocations: list[sqlite3.Row]) -> list[TimelineEvent]:
    events: list[TimelineEvent] = []
    for row in allocations:
        amount = row["allocated_cents"]
        if amount == 0:
            # A zero allocation is a denied claim line carrying no money. An event
            # saying $0.00 moved implies a payment happened; nothing is truer.
            continue
        bank = json.loads(row["bank_canonical"]) if row["bank_canonical"] else {}
        facts = {
            "direction": "OUT" if amount < 0 else "IN",
            "track": (
                "REBATE" if row["parent_kind"] == str(RecordKind.REBATE_BATCH)
                else "REIMBURSEMENT"
            ),
            # Which basis resolved the link. A TRN02 match and an amount-and-date
            # match are not equally strong claims, so the basis travels with the money.
            "basis": row["basis"],
            "allocated_cents": amount,
        }
        for name in ("ach_trace_number", "trn02"):
            if _present(row[name]):
                facts[name] = row[name]
        if _present(bank.get("posting_date")):
            facts["posting_date"] = bank["posting_date"]

        events.append(
            TimelineEvent(
                at=row["caused_by_received_at"],
                occurred_on=bank.get("posting_date"),
                tag="CASH",
                facts=facts,
                # Which way the money went, on which track, how much, and how
                # confidently it was linked. The trace numbers are identity.
                essential=("direction", "track", "allocated_cents", "basis"),
                source={"ach_trace_number": row["ach_trace_number"], "trn02": row["trn02"]},
            )
        )
    return events


# ═══ verdicts, as transitions ══════════════════════════════════════════════


def _verdict_events(verdicts) -> list[TimelineEvent]:
    """Only the changes.

    An episode evaluated monthly has a dozen identical verdict rows; listing them
    all buries the two that matter.  What an operator wants is the moments the
    answer *moved*.  The full log is returned separately.
    """
    events: list[TimelineEvent] = []
    previous = None
    for verdict in verdicts:
        signature = (
            verdict.reimbursement_verdict_code,
            verdict.rebate_verdict_code,
            verdict.episode_disposition.value,
            tuple(code.value for code in verdict.reasons),
        )
        if previous is not None and signature == previous:
            continue

        facts: dict[str, Any] = {
            "transition": "FIRST" if previous is None else "CHANGED",
            "reimbursement_verdict": verdict.reimbursement_verdict_code,
            "rebate_verdict": verdict.rebate_verdict_code,
            "episode_disposition": verdict.episode_disposition.value,
        }
        reasons = [code.value for code in verdict.reasons]
        if reasons:
            facts["reason_codes"] = reasons
        flags = [flag.code for flag in verdict.cross_track_flags]
        if flags:
            facts["cross_track_flags"] = flags
        if previous is not None:
            facts["previous_reimbursement_verdict"] = previous[0]
            facts["previous_rebate_verdict"] = previous[1]
            facts["previous_disposition"] = previous[2]
        if verdict.reopened_from:
            # Reopened is a flag, not a fourth disposition -- so it is a fact on the
            # transition rather than a different kind of event.
            facts["transition"] = "REOPENED"
            facts["reopened_from"] = verdict.reopened_from.value
            if _present(verdict.previously_closed_at):
                facts["previously_closed_at"] = verdict.previously_closed_at

        events.append(
            TimelineEvent(
                at=verdict.cursor_at,
                occurred_on=None,
                tag="VERDICT",
                facts=facts,
                # A verdict is already the short version of itself -- everything on
                # it is the story. Only the `previous_*` fields are context a short
                # view can drop, since the transition label already says it moved.
                essential=tuple(
                    name for name in facts if not name.startswith("previous_")
                ),
            )
        )
        previous = signature
    return events
