"""The episode dossier: one call, one episode, its entire history.

This is the object the whole design points at.  An episode is the unit of reconciliation, and
everything else — records, verdicts, cash, keys, parks — hangs off it.  Until now those lived in
six tables and were assembled ad hoc by whoever needed them.  This module assembles them **once**,
into the shape a human reads and the agent layer consumes, so both work from the same picture.

═══ Why it is a merged timeline rather than six lists ══════════════════════════════

The question an operator actually asks is *"what happened to this claim?"* — and the answer runs in
one direction, through time, mixing things that happened in the outside world with things we
concluded about them:

    2 Sep    the claim was filed and the PBM accepted it
    18 Sep   the payer's remittance said it paid, short by $500
    17 Sep   the money arrived, matching what the remittance promised
    4 Oct    the TPA said the dispense qualified for 340B
    2 Nov    the manufacturer paid the rebate
    6 Nov    a later remittance clawed $412.60 back, netted, invisible to the bank
    6 Nov    we reopened it: this had been closed since 1 October

Six separate lists cannot be read that way.  A merged, ordered narrative can.

═══ Two clocks, and why both are shown ════════════════════════════════════════════

Every event carries **when we learned it** (``at``, the arrival time) and, where one exists, **when
it happened** (``occurred_on``, a native date on the record).  They are routinely different, and the
gap is often the finding: a remittance dated the 17th that reached us on the 30th is a late-arriving
record, and reading only one clock hides it.

The timeline is ordered by ``at``, because that is the order the system could have known things —
which is the same order replay reproduces.

═══ Verdicts appear as *transitions*, not as samples ══════════════════════════════

The engine writes a verdict per (episode, cursor), so an episode evaluated monthly has a dozen rows
saying the same thing.  Listing all of them buries the two that matter.  Only changes are emitted —
the first verdict, and every later one that differs — with what changed spelled out.  The full log
is still returned separately for anyone who wants it.

═══ Nothing here is generated by a model ══════════════════════════════════════════

Every headline is composed in Python from fields the records carry.  The agent layer receives this
and explains it; it does not get to invent any of it, and it never sees a number this module did not
read out of the database.
"""

from __future__ import annotations

import json
import sqlite3
from dataclasses import asdict, dataclass, field
from typing import Any

from recon.db import repository
from recon.domain.enums import RecordKind
from recon.money import format_amount
from recon.reference import codes, drugs, entities

__all__ = ["build_dossier", "TimelineEvent"]


@dataclass
class TimelineEvent:
    """One thing that happened, or one thing we concluded."""

    #: When we learned it. Ordering key, because it is the order replay reproduces.
    at: str
    #: When it happened in the outside world, where the record carries such a date.
    occurred_on: str | None
    kind: str
    headline: str
    detail: str = ""
    amount_cents: int | None = None
    #: Where to look it up: the feed file, the line, the source record id.
    source: dict[str, Any] | None = None
    #: True when arrival lagged the event by more than a fortnight — the late-arrival defect.
    late: bool = False


def build_dossier(conn: sqlite3.Connection, episode_id: str, cursor: str) -> dict[str, Any] | None:
    """Everything known about one episode, as of ``cursor``.

    The cursor is honoured throughout: at an earlier cursor the dossier is genuinely shorter, because
    records that had not arrived are not part of the story yet.  That is the same replay property the
    rest of the system has, applied to the narrative.
    """
    episode = conn.execute(
        "SELECT * FROM episode WHERE episode_id = ?", (episode_id,)
    ).fetchone()
    if episode is None:
        return None

    records = _records(conn, episode_id, cursor)
    allocations = _allocations(conn, episode_id, cursor)
    verdicts = repository.verdict_history(conn, episode_id)
    visible_verdicts = [v for v in verdicts if v.cursor_at <= cursor]

    events: list[TimelineEvent] = []
    events.extend(_record_events(episode, records))
    events.extend(_cash_events(allocations))
    events.extend(_verdict_events(visible_verdicts))
    events.sort(key=lambda event: (event.at, event.kind))

    latest = visible_verdicts[-1] if visible_verdicts else None
    return {
        "episode_id": episode_id,
        "cursor": cursor,
        "identity": _identity(episode),
        "current": _current(latest),
        "economics": _economics(latest),
        "timeline": [asdict(event) for event in events],
        "counts": {
            "records": len(records),
            "cash_allocations": len(allocations),
            "verdicts_written": len(visible_verdicts),
            "verdict_changes": sum(1 for e in events if e.kind == "VERDICT"),
        },
        # The raw material, for anyone who wants to check the narrative against it.
        "verdict_log": [
            {
                "cursor_at": v.cursor_at,
                "episode_disposition": v.episode_disposition.value,
                "reimbursement_verdict": v.reimbursement_verdict_code,
                "rebate_verdict": v.rebate_verdict_code,
                "reason_codes": [code.value for code in v.reasons],
                "reopened_from": v.reopened_from.value if v.reopened_from else None,
            }
            for v in visible_verdicts
        ],
        "crosswalk_keys": [
            {
                "key_type": row.key_type.value,
                "key_value": row.key_value,
                "first_seen_at": row.first_seen_at,
            }
            for row in repository.crosswalk_for_episode(conn, episode_id)
            if row.first_seen_at <= cursor
        ],
        "unresolved": _unresolved(conn, episode, cursor),
    }


# ═══ identity and headline figures ══════════════════════════════════════════


def _identity(episode: sqlite3.Row) -> dict[str, Any]:
    try:
        drug = drugs.by_ndc(episode["ndc11"])
        drug_name = f"{drug.name} {drug.strength}"
    except Exception:
        drug_name = episode["ndc11"]

    payer_id = episode["pbm_id"] or episode["medical_payer_id"]
    payer_name = payer_id
    try:
        payer_name = (
            entities.pbm_by_id(payer_id).name
            if episode["pbm_id"]
            else entities.payer_by_id(payer_id).name
        )
    except Exception:
        pass

    return {
        "track": episode["reimbursement_track"],
        "drug": drug_name,
        "ndc11": episode["ndc11"],
        "quantity": (episode["quantity_milli"] or 0) // 1000,
        "date_of_service": episode["date_of_service"],
        "payer": payer_name,
        "pharmacy_npi": episode["pharmacy_npi"],
        "rx_number": episode["rx_number"],
        "fill_number": episode["fill_number"],
        "clm01": episode["clm01"],
        "billing_provider_npi": episode["billing_provider_npi"],
        "is_340b_flagged": bool(episode["is_340b_flagged"]),
        "opened_at": episode["created_from_received_at"],
    }


def _current(latest) -> dict[str, Any] | None:
    if latest is None:
        return None
    return {
        "reimbursement_verdict": latest.reimbursement_verdict_code,
        "rebate_verdict": latest.rebate_verdict_code,
        "episode_disposition": latest.episode_disposition.value,
        "reason_codes": [code.value for code in latest.reasons],
        "cross_track_flags": [flag.code for flag in latest.cross_track_flags],
        "reopened_from": latest.reopened_from.value if latest.reopened_from else None,
        "as_of": latest.cursor_at,
    }


def _economics(latest) -> dict[str, Any] | None:
    if latest is None:
        return None
    return {
        "expected_reimbursement_cents": latest.expected_reimbursement_cents,
        "received_reimbursement_cents": latest.received_reimbursement_cents,
        "reimbursement_variance_cents": latest.reimbursement_variance_cents,
        "expected_rebate_cents": latest.expected_rebate_cents,
        "received_rebate_cents": latest.received_rebate_cents,
        "rebate_variance_cents": latest.rebate_variance_cents,
    }


# ═══ fetching ═══════════════════════════════════════════════════════════════


def _records(conn: sqlite3.Connection, episode_id: str, cursor: str) -> list[sqlite3.Row]:
    """Every record that resolved to this episode, in arrival order.

    Driven by ``ix_crosswalk_episode`` — the crosswalk already knows what points here, so this is a
    seek rather than a hunt through the record table.
    """
    return conn.execute(
        "SELECT DISTINCT n.norm_id, n.raw_id, n.record_kind, n.source_system, n.received_at,"
        "       n.amount_cents, n.status_code, n.canonical, n.date_of_service, n.clp07,"
        "       n.rx_number, n.authorization_number, n.allocation_code, n.trn02,"
        "       r.source_record_id, r.source_line_no, b.source_file"
        "  FROM crosswalk_key k"
        "  JOIN normalized_record n ON n.norm_id = k.resolved_from_norm_id"
        "  JOIN raw_record r ON r.raw_id = n.raw_id"
        "  JOIN ingest_batch b ON b.batch_id = r.batch_id"
        " WHERE k.episode_id = :episode_id AND n.received_at <= :cursor"
        " ORDER BY n.received_at, n.norm_id",
        {"episode_id": episode_id, "cursor": cursor},
    ).fetchall()


def _allocations(conn: sqlite3.Connection, episode_id: str, cursor: str) -> list[sqlite3.Row]:
    return conn.execute(
        "SELECT a.allocated_cents, a.basis, a.caused_by_received_at,"
        "       bank.canonical AS bank_canonical, bank.ach_trace_number, bank.trn02,"
        "       parent.record_kind AS parent_kind"
        "  FROM cash_allocation a"
        "  JOIN normalized_record bank ON bank.norm_id = a.bank_norm_id"
        "  LEFT JOIN normalized_record parent ON parent.norm_id = a.remittance_norm_id"
        " WHERE a.episode_id = :episode_id AND a.caused_by_received_at <= :cursor"
        " ORDER BY a.caused_by_received_at, a.allocation_id",
        {"episode_id": episode_id, "cursor": cursor},
    ).fetchall()


def _unresolved(conn: sqlite3.Connection, episode: sqlite3.Row, cursor: str) -> list[dict[str, Any]]:
    """Records that *tried* to reach this episode and could not.

    A crosswalk miss leaves nothing attached to the episode, so by definition it cannot appear in the
    timeline — which is precisely why it needs saying somewhere.  These are parked records whose keys
    overlap this episode's natural key, i.e. documents that are probably about this claim but whose
    identifiers did not match.  D-6, from the episode's point of view.
    """
    if not episode["rx_number"]:
        return []
    rows = conn.execute(
        "SELECT DISTINCT p.record_kind, p.park_reason, p.received_at, k.key_type, k.key_value"
        "  FROM parked_record p"
        "  JOIN parked_record_key k ON k.parked_id = p.parked_id"
        "  LEFT JOIN parked_record_resolution r ON r.parked_id = p.parked_id"
        " WHERE r.parked_id IS NULL AND p.received_at <= :cursor"
        "   AND k.key_value LIKE :like"
        " ORDER BY p.received_at",
        {"cursor": cursor, "like": f"%{episode['rx_number']}%"},
    ).fetchall()
    return [
        {
            "record_kind": row["record_kind"],
            "park_reason": row["park_reason"],
            "received_at": row["received_at"],
            "key_type": row["key_type"],
            "key_value": row["key_value"],
        }
        for row in rows
    ]


# ═══ turning records into sentences ════════════════════════════════════════


def _source(row: sqlite3.Row) -> dict[str, Any]:
    return {
        "file": row["source_file"],
        "line": row["source_line_no"],
        "record_id": row["source_record_id"],
        "norm_id": row["norm_id"],
        "raw_id": row["raw_id"],
    }


def _is_late(received_at: str, occurred_on: str | None) -> bool:
    """Arrival lagging the event by more than a fortnight — the D-2 shape."""
    if not occurred_on:
        return False
    from datetime import date

    try:
        return (date.fromisoformat(received_at[:10]) - date.fromisoformat(occurred_on)).days > 14
    except ValueError:
        return False


def _record_events(episode: sqlite3.Row, records: list[sqlite3.Row]) -> list[TimelineEvent]:
    events: list[TimelineEvent] = []
    for row in records:
        kind = RecordKind(row["record_kind"])
        body = json.loads(row["canonical"])
        builder = _BUILDERS.get(kind)
        if builder is None:
            continue
        headline, detail, amount = builder(episode, row, body)
        occurred = row["date_of_service"]
        events.append(
            TimelineEvent(
                at=row["received_at"],
                occurred_on=occurred,
                kind=_EVENT_KIND.get(kind, kind.value),
                headline=headline,
                detail=detail,
                amount_cents=amount,
                source=_source(row),
                late=_is_late(row["received_at"], occurred),
            )
        )
    return events


def _pharmacy_claim(episode, row, body) -> tuple[str, str, int | None]:
    if body.get("response_status") == "P":
        paid = body.get("total_amount_paid_cents")
        headline = "Claim filed and accepted at the point of sale"
        detail = (
            f"The PBM adjudicated it in real time and authorised "
            f"{body.get('bin') and ''}{row['authorization_number'] or 'the claim'}. "
            f"Plan pays {format_amount(paid or 0)}; "
            f"patient pays {format_amount(body.get('patient_pay_amount_cents') or 0)}."
        )
        if body.get("submission_clarification_code") == "20":
            detail += " The pharmacy flagged it as a 340B-related dispense (NCPDP 420-DK = 20)."
        return headline, detail, paid
    rejects = ", ".join(body.get("reject_codes") or []) or "no code given"
    return (
        "Claim rejected at the point of sale",
        f"Reject code {rejects}. A POS rejection is real-time and terminal — no payment, no "
        f"reversal and no settlement can follow, and the drug was not dispensed.",
        0,
    )


def _pharmacy_reversal(episode, row, body) -> tuple[str, str, int | None]:
    return (
        "Pharmacy reversed the claim",
        f"NCPDP B2, reason {body.get('reversal_reason') or 'unstated'}. The reversal carries no "
        f"identity of its own — it matches by repeating the transaction key. The drug did not reach "
        f"the patient, so any 340B rebate resting on this dispense is now invalid rather than merely "
        f"unmatched.",
        None,
    )


def _remittance_line(episode, row, body) -> tuple[str, str, int | None]:
    paid = body.get("payment_cents") or 0
    charged = body.get("charge_cents") or 0
    adjustments = sum(a.get("amount_cents", 0) for a in body.get("adjustments", []))
    residual = charged - paid - adjustments
    status = body.get("clp02_claim_status_code")

    settlement = ""
    if status == codes.CLP02_PAID_PRIMARY:
        settlement = " CLP02 is “1”: processed as primary and final, so the receivable is closed."
    elif status in codes.clp02_settlement_unconfirmed():
        settlement = (
            f" CLP02 is “{status}”: money moved but the receivable is *not* closed. "
            f"Settlement is missing unless a later “1” line arrives for this claim."
        )
    elif status == codes.CLP02_DENIED:
        settlement = " CLP02 is “4”: denied."

    reasons = ", ".join(
        f"{a['group_code']}-{a['reason_code']} {format_amount(a['amount_cents'])}"
        for a in body.get("adjustments", [])
    )
    residual_note = ""
    if residual > 0:
        residual_note = (
            f" {format_amount(residual)} of the charge is left unexplained by the adjustments — "
            f"that residual is what makes this an underpayment rather than a contractual write-down."
        )
    elif residual < 0:
        residual_note = f" The line carries {format_amount(-residual)} more than the charge supports."

    return (
        f"Payer's remittance says it paid {format_amount(paid)}",
        f"Charged {format_amount(charged)}; adjustments {reasons or 'none'}.{settlement}{residual_note}",
        paid,
    )


def _provider_level_adjustment(episode, row, body) -> tuple[str, str, int | None]:
    amount = body.get("amount_cents") or 0
    reason = body.get("reason_code")
    reference = body.get("reference")
    try:
        semantics = codes.plb_semantics(reason)
        meaning = semantics.description
    except KeyError:
        meaning = "provider-level adjustment"

    traceable = (
        f"It references {reference}, so it can be tied back to the claim it recovers against."
        if reference
        else (
            "It carries no reference at all, so it cannot be tied to any claim — the residual has to "
            "be tracked as unexplained rather than silently absorbed."
        )
    )
    return (
        f"Provider-level adjustment {reason}: {format_amount(abs(amount))}",
        f"{meaning}. This is netted out of the batch total rather than appearing as its own bank "
        f"movement — so the deposit is simply smaller and nothing on the bank side says why. "
        f"{traceable}",
        -abs(amount) if amount > 0 else abs(amount),
    )


def _medical_submission(episode, row, body) -> tuple[str, str, int | None]:
    frequency = body.get("frequency_code", "1")
    if frequency == "1":
        return (
            "Claim submitted to the payer on an 837",
            "The drug was already administered — on the medical benefit the dispense happens before "
            "the billing, so a billing failure here does not undo it.",
            row["amount_cents"],
        )
    if frequency == "7":
        return (
            "Replacement claim submitted (frequency 7)",
            f"A full replacement, not a patch: anything this leaves out is deleted from the payer's "
            f"record. It points back at ICN {body.get('ref_f8_original_icn')}. X12 has no field "
            f"anywhere that says “this is an appeal” — a resubmission like this is what one "
            f"actually looks like on the wire.",
            row["amount_cents"],
        )
    return (
        "Claim voided (frequency 8)",
        f"Cancels ICN {body.get('ref_f8_original_icn')}. A void carries no clinical content of its "
        f"own; it exists only to withdraw the claim.",
        None,
    )


def _medical_acknowledgment(episode, row, body) -> tuple[str, str, int | None]:
    if body.get("accepted"):
        return (
            "Clearinghouse accepted the claim",
            f"277CA {body.get('stc01_composite')}. The payer now has it and a remittance should "
            f"follow. Without this acknowledgment, “accepted and waiting” would be "
            f"indistinguishable from “rejected before the payer ever saw it”.",
            None,
        )
    return (
        "Clearinghouse rejected the claim",
        f"277CA {body.get('stc01_composite')} — {body.get('stc12_free_form')}. The payer never saw "
        f"it, so there is no denial to appeal and no ICN was ever assigned. Resubmission is the "
        f"action. The drug was still administered, so a 340B rebate may legitimately exist.",
        0,
    )


def _tpa_qualification(episode, row, body) -> tuple[str, str, int | None]:
    status = body.get("qualification_status")
    if status == "QUALIFIED":
        return (
            "TPA qualified the dispense for 340B",
            "The first of two gates. The TPA decides qualification; the manufacturer separately "
            "decides whether to approve and pay, and it can still refuse.",
            None,
        )
    if status == "NOT_QUALIFIED":
        return (
            "TPA did not qualify the dispense",
            f"Reason: {body.get('disqualification_reason')}. Expected rebate falls to zero. This is "
            f"a correct outcome rather than a failure — not every dispense qualifies.",
            0,
        )
    return (
        "Dispense sent to the TPA; no decision yet",
        "It is sitting at the first gate. Being stuck here is a reason code, never a timer.",
        None,
    )


def _tpa_request(episode, row, body) -> tuple[str, str, int | None]:
    submitted = body.get("submission_date")
    return (
        "Rebate request submitted to the manufacturer",
        f"Submitted {submitted}. This record is what separates “qualified but not yet "
        f"submitted” from “submitted and awaiting a decision” — without it the two are "
        f"identical on the wire.",
        None,
    )


def _tpa_decision(episode, row, body) -> tuple[str, str, int | None]:
    status = body.get("manufacturer_status")
    if status == "APPROVED":
        return (
            "Manufacturer approved the rebate",
            "Approval and payment are separate events; the money may still not arrive.",
            None,
        )
    return (
        "Manufacturer rejected the rebate",
        f"Reason: {body.get('rejection_reason')}. The qualification stood — this is the "
        f"manufacturer disputing it, which is a different argument with a different counterparty.",
        0,
    )


def _tpa_reversal(episode, row, body) -> tuple[str, str, int | None]:
    return (
        "Dispense reversed at the TPA",
        f"Negative quantity {body.get('quantity_dispensed')}, reason "
        f"{body.get('reversal_reason')}. A reversal is a negative line, not a deletion — the "
        f"original record stays.",
        None,
    )


def _rebate_line(episode, row, body) -> tuple[str, str, int | None]:
    amount = body.get("rebate_amount_cents") or 0
    return (
        f"Manufacturer paid a rebate of {format_amount(amount)}",
        f"Paid inside a batch covering many dispenses, under allocation code "
        f"{row['allocation_code']}. The batch total has to be split back across its dispenses — the "
        f"same splitter the bank feed needs.",
        amount,
    )


_BUILDERS = {
    RecordKind.PHARMACY_CLAIM: _pharmacy_claim,
    RecordKind.PHARMACY_REVERSAL: _pharmacy_reversal,
    RecordKind.REMITTANCE_CLAIM_LINE: _remittance_line,
    RecordKind.PROVIDER_LEVEL_ADJUSTMENT: _provider_level_adjustment,
    RecordKind.MEDICAL_SUBMISSION: _medical_submission,
    RecordKind.MEDICAL_ACKNOWLEDGMENT: _medical_acknowledgment,
    RecordKind.TPA_QUALIFICATION: _tpa_qualification,
    RecordKind.TPA_REBATE_REQUEST: _tpa_request,
    RecordKind.TPA_MANUFACTURER_DECISION: _tpa_decision,
    RecordKind.TPA_REVERSAL: _tpa_reversal,
    RecordKind.REBATE_DISPENSE_LINE: _rebate_line,
}

_EVENT_KIND = {
    RecordKind.PHARMACY_CLAIM: "CLAIM",
    RecordKind.PHARMACY_REVERSAL: "REVERSAL",
    RecordKind.REMITTANCE_CLAIM_LINE: "REMITTANCE",
    RecordKind.PROVIDER_LEVEL_ADJUSTMENT: "CLAWBACK",
    RecordKind.MEDICAL_SUBMISSION: "CLAIM",
    RecordKind.MEDICAL_ACKNOWLEDGMENT: "ACKNOWLEDGMENT",
    RecordKind.TPA_QUALIFICATION: "REBATE",
    RecordKind.TPA_REBATE_REQUEST: "REBATE",
    RecordKind.TPA_MANUFACTURER_DECISION: "REBATE",
    RecordKind.TPA_REVERSAL: "REVERSAL",
    RecordKind.REBATE_DISPENSE_LINE: "REBATE",
}


# ═══ cash ═══════════════════════════════════════════════════════════════════

_BASIS_NOTE = {
    "TRN02": "matched on the payer's reassociation trace number — the strong link",
    "ALLOCATION_CODE": "matched on the rebate batch's allocation code",
    "AMOUNT_DATE": (
        "matched on amount and date alone, because the CCD+ addenda were lost in transit and the "
        "deposit carried no business reference at all — a weaker match, recorded as such"
    ),
    "ACH_TRACE": "matched on the ACH trace number",
    "RESIDUAL": "not attributable to any claim — tracked as an unexplained residual",
}


def _cash_events(allocations: list[sqlite3.Row]) -> list[TimelineEvent]:
    events: list[TimelineEvent] = []
    for row in allocations:
        amount = row["allocated_cents"]
        if amount == 0:
            # A zero allocation is a denied claim line carrying no money. Reporting "cash arrived:
            # $0.00" is worse than saying nothing -- it implies a payment happened.
            continue
        bank = json.loads(row["bank_canonical"]) if row["bank_canonical"] else {}
        basis = row["basis"]
        is_rebate = row["parent_kind"] == str(RecordKind.REBATE_BATCH)
        leaving = amount < 0

        if leaving:
            headline = f"{format_amount(abs(amount))} went back out"
        else:
            what = "Rebate cash" if is_rebate else "Cash"
            headline = f"{what} arrived: {format_amount(amount)}"

        events.append(
            TimelineEvent(
                at=row["caused_by_received_at"],
                occurred_on=bank.get("posting_date"),
                kind="CASH",
                headline=headline,
                detail=(
                    f"Allocated to this episode from a deposit that covered many claims — "
                    f"{_BASIS_NOTE.get(basis, basis)}. "
                    f"A bank line carries no claim identifier at all, so it resolves in two hops: "
                    f"reference to remittance, remittance to its claim list."
                ),
                amount_cents=amount,
                source={"ach_trace_number": row["ach_trace_number"], "trn02": row["trn02"]},
            )
        )
    return events


# ═══ verdicts, as transitions ══════════════════════════════════════════════


def _verdict_events(verdicts) -> list[TimelineEvent]:
    """Only the changes.

    An episode evaluated monthly has a dozen identical verdict rows; listing them all buries the two
    that matter. What an operator wants is the moments the answer *moved*.
    """
    events: list[TimelineEvent] = []
    previous = None
    for verdict in verdicts:
        signature = (
            verdict.reimbursement_verdict_code,
            verdict.rebate_verdict_code,
            verdict.episode_disposition.value,
            tuple(code.value for code in verdict.reasons),
        )
        if previous is not None and signature == previous:
            continue

        reasons = ", ".join(code.value for code in verdict.reasons) or "no defect"
        if previous is None:
            headline = (
                f"First verdict: {verdict.reimbursement_verdict_code} / "
                f"{verdict.rebate_verdict_code} — {verdict.episode_disposition.value}"
            )
            detail = f"Reasons: {reasons}."
        else:
            headline = (
                f"Verdict changed to {verdict.reimbursement_verdict_code} / "
                f"{verdict.rebate_verdict_code} — {verdict.episode_disposition.value}"
            )
            detail = (
                f"Was {previous[0]} / {previous[1]} ({previous[2]}). Now: {reasons}. "
                f"A verdict only moves when a new record arrives — an untouched episode cannot "
                f"change, which is what makes incremental processing provably complete."
            )

        if verdict.reopened_from:
            headline = f"Reopened from {verdict.reopened_from.value}"
            detail = (
                f"This episode had been {verdict.reopened_from.value} since "
                f"{verdict.previously_closed_at}, and new information moved it backwards to "
                f"{verdict.episode_disposition.value}. Reopened is a flag rather than a fourth "
                f"queue — and money already recognised, now at risk, outranks money never "
                f"collected. Now: {reasons}."
            )

        events.append(
            TimelineEvent(
                at=verdict.cursor_at,
                occurred_on=None,
                kind="VERDICT",
                headline=headline,
                detail=detail,
            )
        )
        previous = signature
    return events
